### PR TITLE
Update usage.py

### PR DESCRIPTION
**Pull request by alanyee**
Using the args instead of len(args)

### CODE REVIEW

**Comment by alanyee** [comment]
Could I get some clarity of your comment here:
```
This hackery is due to `argparse` allowing only positional args to be required
    Named arguments are more descriptive
```

**Comment by KevinHock** [comment]
Sure, arguments `--passed-in-like-this` can't be required if I recall, only things passed in positionally, I made it so that one has to do e.g. `-t` or `--target`.

**Comment by KevinHock** [comment]
Also there is a bug right now on master, that is not present on the PyPI released versions, I will push the fix today or tomorrow (CA time).

**Comment by alanyee** [comment]
@KevinHock `required=True` is not what you are looking for?

**Comment by KevinHock** [comment]
Hmm, I did do `required=True` 

I can try it later, but if you remove
```python
parser._action_groups[1]._group_actions = []
```
and see the difference that it makes, in e.g. `--help` output, that's probably the reason.

**Comment by KevinHock** [comment]
Commenting out the argparse hacks yields 
```diff
terminal:TrustTrees kevin$ gd trusttrees/usage.py 
diff --git a/trusttrees/usage.py b/trusttrees/usage.py
index f349e8a..e49ac1d 100644
--- a/trusttrees/usage.py
+++ b/trusttrees/usage.py
@@ -92,10 +92,10 @@ def parse_args(args):
     Named arguments are more descriptive
     """
     # Remove --help from the mutually exclusive required arguments group
-    parser._action_groups[1]._group_actions = []
+    # parser._action_groups[1]._group_actions = []
     _add_mutually_exclusive_required_args(parser)
     # `add_mutually_exclusive_group` does not accept a title, so change it
-    parser._action_groups[1].title = 'mutually exclusive required arguments'
+    # parser._action_groups[1].title = 'mutually exclusive required arguments'
 
     _add_optional_args(parser)
 ```


```
terminal:TrustTrees kevin$ python -m trusttrees -h
usage: trusttrees [-h] (-t TARGET_HOSTNAME | -l TARGET_HOSTNAMES_LIST) [-o]
                  [--only-problematic] [--no-graphing] [-x EXPORT_FORMATS]
                  [--resolvers RESOLVERS_FILE]
                  [--aws-credentials AWS_CREDS_FILE]
                  [--gandi-api-v4-key GANDI_API_V4_KEY]
                  [--gandi-api-v5-key GANDI_API_V5_KEY]

Graph out a domain's DNS delegation chain and trust trees!

optional arguments:
  -h, --help            show this help message and exit
  -t TARGET_HOSTNAME, --target TARGET_HOSTNAME
                        Target hostname to generate delegation graph from.
  -l TARGET_HOSTNAMES_LIST, --target-list TARGET_HOSTNAMES_LIST
                        Text file with a list of target hostnames.

optional arguments:
  -o, --open            Open the generated graph(s) once run.
  --only-problematic    Open generate graphs that are likely to be vulnerable.
  --no-graphing         Do not generate any graphs.
  -x EXPORT_FORMATS, --export-formats EXPORT_FORMATS
                        Comma-separated export formats, e.g: -x png,pdf
  --resolvers RESOLVERS_FILE
                        Text file containing DNS resolvers to use.

optional arguments for domain-checking:
  --aws-credentials AWS_CREDS_FILE
                        AWS credentials JSON file for checking if nameserver
                        base domains are registerable.
  --gandi-api-v4-key GANDI_API_V4_KEY
                        Gandi API V4 key for checking if nameserver base
                        domains are registerable.
  --gandi-api-v5-key GANDI_API_V5_KEY
                        Gandi API V5 key for checking if nameserver base
                        domains are registerable.
```

You'll see `--help` is automatically in the first group, and that it's named `optional arguments:`, which isn't what we want. We could add a separate argument group, then add a mutually exclusive group to it in order to get a proper title (not `optional arguments:`), but then we would list help by itself, on top of all other argument groups, including the required ones. If a user is able to see the `--help` screen, my thinking was that seeing `--help` is an option isn't the most important thing they should see, since it's how they got to the `--help` output. So I just removed it to get

```kevins-mbp:TrustTrees kevin$ python -m trusttrees -h
usage: trusttrees [-h] (-t TARGET_HOSTNAME | -l TARGET_HOSTNAMES_LIST) [-o]
                  [--only-problematic] [--no-graphing] [-x EXPORT_FORMATS]
                  [--resolvers RESOLVERS_FILE]
                  [--aws-credentials AWS_CREDS_FILE]
                  [--gandi-api-v4-key GANDI_API_V4_KEY]
                  [--gandi-api-v5-key GANDI_API_V5_KEY]

Graph out a domain's DNS delegation chain and trust trees!

mutually exclusive required arguments:
  -t TARGET_HOSTNAME, --target TARGET_HOSTNAME
                        Target hostname to generate delegation graph from.
  -l TARGET_HOSTNAMES_LIST, --target-list TARGET_HOSTNAMES_LIST
                        Text file with a list of target hostnames.

optional arguments:
  -o, --open            Open the generated graph(s) once run.
  --only-problematic    Open generate graphs that are likely to be vulnerable.
  --no-graphing         Do not generate any graphs.
  -x EXPORT_FORMATS, --export-formats EXPORT_FORMATS
                        Comma-separated export formats, e.g: -x png,pdf
  --resolvers RESOLVERS_FILE
                        Text file containing DNS resolvers to use.

optional arguments for domain-checking:
  --aws-credentials AWS_CREDS_FILE
                        AWS credentials JSON file for checking if nameserver
                        base domains are registerable.
  --gandi-api-v4-key GANDI_API_V4_KEY
                        Gandi API V4 key for checking if nameserver base
                        domains are registerable.
  --gandi-api-v5-key GANDI_API_V5_KEY
                        Gandi API V5 key for checking if nameserver base
                        domains are registerable.
```

**Comment by alanyee** [comment]
@KevinHock Please correct me if I have misunderstood: the point of "this hackery" is remove `-h` and `--help` from your help message.

**Comment by KevinHock** [comment]
@alanyee  Specifically the first, required group, yes.

**Pull request merged**
